In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("./src/data/raw/Video_Game_Sales_as_of_Jan_2017.csv")

In [6]:
#Ver las primeras filas
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54,76.0,51.0,8.0,324.0,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.80,3.79,3.29,35.57,82.0,73.0,8.3,712.0,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.95,3.28,2.95,32.78,80.0,73.0,8.0,193.0,E
4,Pokemon Red/Pokemon Blue,G,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN

In [7]:
#Informacion general del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17416 entries, 0 to 17415
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             17416 non-null  object
 1   Platform         17416 non-null  object
 2   Year_of_Release  17408 non-null  float64
 3   Genre            17416 non-null  object
 4   Publisher        17415 non-null  object
 5   NA_Sales         17416 non-null  float64
 6   EU_Sales         17416 non-null  float64
 7   JP_Sales         17416 non-null  float64
 8   Other_Sales      17416 non-null  float64
 9   Global_Sales     17416 non-null  float64
 10  Critic_Score     8336 non-null   float64
 11  Critic_Count     8336 non-null   float64
 12  User_Score       7798 non-null   float64
 13  User_Count       7798 non-null   float64
 14  Rating           10252 non-null  object
dtypes: float64(10), object(5)
memory usage: 2.0+ MB

In [8]:
#Identificar columnas de texto
columnas_texto = df.select_dtypes(include="object").columns
columnas_texto

Index(['Name', 'Platform', 'Genre', 'Publisher', 'Rating'], dtype='object')

In [9]:
#Convertir en nulos los valores que empiezan por espacio
for col in columnas_texto:
    df[col] = df[col].replace(r"^\s+.*", np.nan, regex=True)

In [10]:
#Comprobamos los nulos tras la conversión
df.isnull().sum()

Name                  0
Platform              0
Year_of_Release       8
Genre                 0
Publisher             1
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       9080
Critic_Count       9080
User_Score         9618
User_Count         9618
Rating             7164
dtype: int64

In [11]:
#identificar valores faltantes
df.isnull().sum()

Name                  0
Platform              0
Year_of_Release       8
Genre                 0
Publisher             1
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       9080
Critic_Count       9080
User_Score         9618
User_Count         9618
Rating             7164
dtype: int64

In [12]:
#Como queremos mantener ciertas columnas que tienen mucha cantidad de nulos
#creamos una lista de columnas permitidas
columnas_con_nulos_permitidos = [
    "Critic_Score",
    "Critic_Count",
    "User_Score",
    "User_Count",
    "Rating"
]

In [13]:
#Eliminamos las filas con nulos en el resto de columnas
df = df.dropna(subset=[
    col for col in df.columns 
    if col not in columnas_con_nulos_permitidos
])

In [14]:
#En relacion con las columnas que hemos mantenido, creamos una nueva que 
# indique SI / NO
df["Critica_Profesional"] = np.where(
    df["Critic_Score"].notnull() & df["Critic_Count"].notnull(),
    "Sí",
    "No"
)

In [15]:
df["Critica_Usuario"] = np.where(
    df["User_Score"].notnull() & df["User_Count"].notnull(),
    "Sí",
    "No"
)

In [16]:
df["Tiene_Rating"] = np.where(
    df["Rating"].notnull(),
    "Sí",
    "No"
)

In [17]:
#Comprobamos las nuevas columnas
df[[
    "Critic_Score", "Critic_Count", "Critica_Profesional",
    "User_Score", "User_Count", "Critica_Usuario",
    "Rating", "Tiene_Rating"
]].head()

,Critic_Score,Critic_Count,Critica_Profesional,User_Score,User_Count,Critica_Usuario,Rating,Tiene_Rating
0,76.0,51.0,Sí,8.0,324.0,Sí,E,Sí
1,NaN,NaN,No,NaN,NaN,No,NaN,No
2,82.0,73.0,Sí,8.3,712.0,Sí,E,Sí
3,80.0,73.0,Sí,8.0,193.0,Sí,E,Sí
4,NaN,NaN,No,NaN,NaN,No,NaN,No

In [18]:
#ver si hay duplicados
df.duplicated().sum()

np.int64(0)

In [19]:
#ver los duplicados
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Platform, Year_of_Release, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales, Critic_Score, Critic_Count, User_Score, User_Count, Rating, Critica_Profesional, Critica_Usuario, Tiene_Rating]
Index: []

In [20]:
#eliminar duplicados
df = df.drop_duplicates()

In [21]:
#mirar estadisticas básicas
df.describe()

,Year_of_Release,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count
count,17408.000000,17408.000000,17408.000000,17408.000000,17408.000000,17408.000000,8335.000000,8335.000000,7798.000000,7798.000000
mean,2006.630859,0.254651,0.140791,0.075044,0.045929,0.516695,68.914337,26.194721,7.117056,162.672480
std,5.901598,0.800838,0.497446,0.303480,0.183972,1.526439,13.964819,18.991109,1.502410,562.837954
min,1976.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,0.000000,4.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.050000,60.000000,11.000000,6.400000,10.000000
50%,2008.000000,0.070000,0.020000,0.000000,0.010000,0.160000,71.000000,21.000000,7.500000,25.000000
75%,2011.000000,0.230000,0.100000,0.030000,0.030000,0.450000,79.000000,36.000000,8.200000,81.000000
max,2017.000000,41.360000,28.960000,10.220000,10.570000,82.540000,98.000000,113.000000,9.700000,10766.000000

In [22]:
Q1 = df["Global_Sales"].quantile(0.25)
Q3 = df["Global_Sales"].quantile(0.75)
IQR = Q3 - Q1

In [23]:
#filtrar outliers
df = df[
    (df["Global_Sales"] >= Q1 - 1.5 * IQR) &
    (df["Global_Sales"] <= Q3 + 1.5 * IQR)
]

In [24]:
#tipos de datos
df.dtypes

Name                    object
Platform                object
Year_of_Release        float64
Genre                   object
Publisher               object
NA_Sales               float64
EU_Sales               float64
JP_Sales               float64
Other_Sales            float64
Global_Sales           float64
Critic_Score           float64
Critic_Count           float64
User_Score             float64
User_Count             float64
Rating                  object
Critica_Profesional     object
Critica_Usuario         object
Tiene_Rating            object
dtype: object

In [25]:
#convertir texto a número
df["Year_of_Release"] = pd.to_numeric(df["Year_of_Release"], errors="coerce")

In [26]:
#convertir a categoria
df["Platform"] = df["Platform"].astype("category")
df["Genre"] = df["Genre"].astype("category")

In [27]:
#normalizacion
df["Global_Sales_norm"] = (
    df["Global_Sales"] - df["Global_Sales"].min()
) / (
    df["Global_Sales"].max() - df["Global_Sales"].min()
)

In [28]:
#estandarizacion
df["Global_Sales_norm"] = (
    df["Global_Sales"] - df["Global_Sales"].min()
) / (
    df["Global_Sales"].max() - df["Global_Sales"].min()
)

In [29]:
#guardamos el data set limpio
df.to_csv("./src/data/video_game_sales_limpio.csv", index=False)