In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("./src/data/raw/Video_Game_Sales_as_of_Jan_2017.csv")

In [4]:
#Ver las primeras filas
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54,76.0,51.0,8.0,324.0,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.80,3.79,3.29,35.57,82.0,73.0,8.3,712.0,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.95,3.28,2.95,32.78,80.0,73.0,8.0,193.0,E
4,Pokemon Red/Pokemon Blue,G,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN

In [5]:
#Informacion general del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17416 entries, 0 to 17415
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             17416 non-null  object
 1   Platform         17416 non-null  object
 2   Year_of_Release  17408 non-null  float64
 3   Genre            17416 non-null  object
 4   Publisher        17415 non-null  object
 5   NA_Sales         17416 non-null  float64
 6   EU_Sales         17416 non-null  float64
 7   JP_Sales         17416 non-null  float64
 8   Other_Sales      17416 non-null  float64
 9   Global_Sales     17416 non-null  float64
 10  Critic_Score     8336 non-null   float64
 11  Critic_Count     8336 non-null   float64
 12  User_Score       7798 non-null   float64
 13  User_Count       7798 non-null   float64
 14  Rating           10252 non-null  object
dtypes: float64(10), object(5)
memory usage: 2.0+ MB

In [6]:
#identificar valores faltantes
df.isnull().sum()

Name                  0
Platform              0
Year_of_Release       8
Genre                 0
Publisher             1
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       9080
Critic_Count       9080
User_Score         9618
User_Count         9618
Rating             7164
dtype: int64

In [7]:
#eliminar las filas que tienen valores nulos
df = df.dropna()

In [8]:
#ver si hay duplicados
df.duplicated().sum()

np.int64(0)

In [9]:
#ver los duplicados
df[df.duplicated()]

Empty DataFrame
Columns: [Name, Platform, Year_of_Release, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales, Critic_Score, Critic_Count, User_Score, User_Count, Rating]
Index: []

In [10]:
#eliminar duplicados
df = df.drop_duplicates()

In [11]:
#mirar estadisticas básicas
df.describe()

,Year_of_Release,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count
count,7112.000000,7112.000000,7112.000000,7112.000000,7112.000000,7112.000000,7112.000000,7112.000000,7112.000000,7112.000000
mean,2007.462317,0.388567,0.232537,0.062652,0.081347,0.765307,70.229471,28.680821,7.176378,174.745922
std,4.231454,0.953982,0.680028,0.283475,0.265864,1.936692,13.896252,19.227119,1.444496,587.113407
min,1985.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,0.500000,4.000000
25%,2004.000000,0.060000,0.020000,0.000000,0.010000,0.110000,62.000000,14.000000,6.500000,11.000000
50%,2007.000000,0.150000,0.060000,0.000000,0.020000,0.290000,72.000000,24.000000,7.500000,27.000000
75%,2011.000000,0.390000,0.202500,0.010000,0.070000,0.742500,80.000000,39.000000,8.200000,88.250000
max,2016.000000,41.360000,28.960000,6.500000,10.570000,82.540000,98.000000,113.000000,9.600000,10766.000000

In [12]:
Q1 = df["Global_Sales"].quantile(0.25)
Q3 = df["Global_Sales"].quantile(0.75)
IQR = Q3 - Q1

In [14]:
#filtrar outliers
df = df[
    (df["Global_Sales"] >= Q1 - 1.5 * IQR) &
    (df["Global_Sales"] <= Q3 + 1.5 * IQR)
]

In [15]:
#tipos de datos
df.dtypes

Name                object
Platform            object
Year_of_Release    float64
Genre               object
Publisher           object
NA_Sales           float64
EU_Sales           float64
JP_Sales           float64
Other_Sales        float64
Global_Sales       float64
Critic_Score       float64
Critic_Count       float64
User_Score         float64
User_Count         float64
Rating              object
dtype: object

In [16]:
#convertir texto a número
df["Year_of_Release"] = pd.to_numeric(df["Year_of_Release"], errors="coerce")

In [17]:
#convertir a categoria
df["Platform"] = df["Platform"].astype("category")
df["Genre"] = df["Genre"].astype("category")

In [18]:
#normalizacion
df["Global_Sales_norm"] = (
    df["Global_Sales"] - df["Global_Sales"].min()
) / (
    df["Global_Sales"].max() - df["Global_Sales"].min()
)

In [19]:
#estandarizacion
df["Global_Sales_norm"] = (
    df["Global_Sales"] - df["Global_Sales"].min()
) / (
    df["Global_Sales"].max() - df["Global_Sales"].min()
)

In [20]:
#guardamos el data set limpio
df.to_csv("./src/data/video_game_sales_limpio.csv", index=False)